# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "openbsd52"
  config.vm.define "openbsd52" do |openbsd|
  end
  config.vm.provision "puppet"
  config.vm.box_url = "https://dl.dropbox.com/s/5ietqc3thdholuh/openbsd-52-64.box"
end
