# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.define "precise" do |precise|
  end
  config.vm.provision "puppet"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
end
